### ISSUE TITLE
Certain XAML files don't export correctly

### ISSUE THREAD

**Issue by DorsalAxe** [CryShana/CryBarEditor#9]
While editing files in UI.bar, I noticed that certain XAML files don't export properly despite appearing correctly in the preview. 

For example, whenever I export Shared.xaml, it creates an incomplete file with some gibberish mixed in. I think it might even be merging in some code from the other UI files? Other files I tried seem to export fine though.

**Comment by CryShana** [comment]
Am not home this weekend to fix this, but will check this on Monday ASAP. 

Thanks for the information.

**Comment by CryShana** [comment]
Managed to fix the bug today. Will release new version 1.0.3 either today or tomorrow.

**Comment by CryShana** [comment]
Fixed now in version 1.0.3, go check it out
